version: '3.0'

services:  
    db:
        image: mongo:4.4.0
        volumes:
            - db-data:/var/lib/mongodb/data
        ports:
            - 27017:27017
    app:
        build: .
        ports:
            - 5000:5000
        depends_on: 
            - db
        links:
            - db
volumes:
    db-data: